[FEAT] Fetch user personal information
algoan/nestjs-bridge-connector pull request #94
Opened 2020-11-16 13:14 UTC by g-ongenae

## Description

- Fetch user personal information from the user connection (`item`) and add the `owner.name` to each account based on its connection (`item.id` / `item_id`).

#### Note

- Requires https://github.com/algoan/rest-nodejs/pull/34

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2020-11-18 16:34 UTC, meriamBenSassi approved these changes
LGTM !

2020-11-18 19:26 UTC, fabong approved these changes
LGTM

2020-11-24 11:27 UTC, ccoeurderoy requested changes
LGTM

2020-11-24 11:27 UTC, ccoeurderoy commented on src/hooks/services/hooks.service.ts
> +    );
Add a try-catch statement to no block the aggregation process if it fails

2020-11-27 17:39 UTC, ccoeurderoy approved these changes
👌 thank you @g-ongenae!

2020-11-27 17:39 UTC, merged